### ISSUE TITLE
NodeInformationRetrievalJob crashes node.js

### ISSUE THREAD

**Issue by baldo** [freifunkhamburg/ffffng#13]
Have to look into this issue. For now disabled on test instance.

**Comment by baldo** [comment]
```
Error: EMFILE, too many open files '/home/fastdform/ffhh/fastdkeys'
    at Object.fs.readdirSync (fs.js:666:18)
    at GlobSync._readdir (/home/fastdform/node_modules/ffffng/node_modules/glob/sync.js:276:41)
    at GlobSync._processReaddir (/home/fastdform/node_modules/ffffng/node_modules/glob/sync.js:136:22)
    at GlobSync._process (/home/fastdform/node_modules/ffffng/node_modules/glob/sync.js:131:10)
    at new GlobSync (/home/fastdform/node_modules/ffffng/node_modules/glob/sync.js:47:10)
    at Function.globSync [as sync] (/home/fastdform/node_modules/ffffng/node_modules/glob/sync.js:25:10)
    at findNodeFiles (/home/fastdform/node_modules/ffffng/server/services/nodeService.js:44:21)
    at findNodeDataByFilePattern (/home/fastdform/node_modules/ffffng/server/services/nodeService.js:266:21)
    at Object.findNodeDataByMac (/home/fastdform/node_modules/ffffng/server/services/nodeService.js:425:20)
    at /home/fastdform/node_modules/ffffng/server/services/monitoringService.js:487:41
    at /home/fastdform/node_modules/ffffng/node_modules/async/dist/async.js:4637:20

```
