### ISSUE TITLE
Node is online in map but offline in ffffng

### ISSUE THREAD

**Issue by baldo** [freifunkhamburg/ffffng#38]
The problem is with node https://map.hamburg.freifunk.net//#!v:m;n:6466b32f0844

**Comment by baldo** [comment]
The error is probably related to:

```
Error retrieving node data:
{
  "message": "Node 448a5b9c85ef: Invalid MAC: undefined",
  "stack": "Error: Node 448a5b9c85ef: Invalid MAC: undefined\n    at /home/fastdform/node_modules/ffffng/server/services/monitoringService.js:172:27\n    at /home/fastdform/node_modules/ffffng/node_modules/lodash/lodash.js:3116:27\n    at /home/fastdform/node_modules/ffffng/node_modules/lodash/lodash.js:4411:15\n    at baseForOwn (/home/fastdform/node_modules/ffffng/node_modules/lodash/lodash.js:2654:24)\n    at /home/fastdform/node_modules/ffffng/node_modules/lodash/lodash.js:4380:18\n    at baseMap (/home/fastdform/node_modules/ffffng/node_modules/lodash/lodash.js:3115:7)\n    at Function.map (/home/fastdform/node_modules/ffffng/node_modules/lodash/lodash.js:8851:14)\n    at parseNodesJson (/home/fastdform/node_modules/ffffng/server/services/monitoringService.js:152:37)\n    at Request._callback (/home/fastdform/node_modules/ffffng/server/services/monitoringService.js:559:17)\n    at Request.self.callback (/home/fastdform/node_modules/ffffng/node_modules/request/request.js:200:22)"
}
```

**Comment by baldo** [comment]
The problem was invalid data in the nodes.json. Closing this for now. Opened ticket #39 for validating the JSON before running into such bugs.
